apiVersion: v1
kind: Pod
metadata:
  name: stock-api
  labels:
    name: stock-api
spec:
  containers:
  - name: stock-api
    image: widgetario/stock-api:21.03
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
