apiVersion: v1
kind: Pod
metadata:
  name: products-db
  labels:
    name: products-db
spec:
  containers:
  - name: products-db
    image: widgetario/products-db:21.03
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
