apiVersion: v1
kind: Pod
metadata:
  name: products-api
  labels:
    name: products-api
spec:
  containers:
  - name: products-api
    image: widgetario/products-api:21.03
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
